### ISSUE TITLE
when downloading on AWS Ireland/Tokyo the download script immediately crashes

### ISSUE THREAD

**Issue by briandoconnor** [HumanCellAtlas/dcp-preview#1]
Testing downloader script from repo version https://github.com/HumanCellAtlas/dcp-preview/commit/a581db93596aa894965eee553ba14d7758ee4089

Using hca cli v3.4.2

Using download script `dcp-preview/download-scripts/hca-dss-download-tmm.sh`

Host is r4.2xlarge, 2TB root partition, AMI Ubuntu 16.04

Region is Ireland and Tokyo on AWS

Immediately after launching the script I get the following error:

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/hca", line 13, in <module>
    cli.main()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/hca/cli.py", line 65, in main
    result = parsed_args.entry_point(parsed_args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/hca/util/__init__.py", line 397, in arg_forwarder
    return command(**command_args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/hca/dss/__init__.py", line 31, in download
    bundle = self.get_bundle(uuid=bundle_uuid, replica=replica, version=version if version else None)["bundle"]
  File "/home/ubuntu/.local/lib/python2.7/site-packages/hca/util/__init__.py", line 149, in __call__
    return self._consume_response(self._request(kwargs))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/hca/util/__init__.py", line 137, in _request
    raise SwaggerAPIException(response=res)
hca.util.exceptions.SwaggerAPIException: not_found: Cannot find file! (HTTP 404). Details:
Traceback (most recent call last):
  File "/var/task/chalicelib/dss/error.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/var/task/chalicelib/dss/api/bundles/__init__.py", line 34, in get
    return get_bundle(uuid, Replica[replica], version, directurls)
  File "/var/task/chalicelib/dss/storage/bundles.py", line 132, in get_bundle
    directurls
  File "/var/task/chalicelib/dss/storage/bundles.py", line 46, in get_bundle_from_bucket
    raise DSSException(404, "not_found", "Cannot find file!")
dss.error.DSSException
```

**Comment by briandoconnor** [comment]
Update, worked with Sam and Hannes on this.  Helped me see that at the time I pulled the script, the HCA CLI was pointed at dev and that setting persisted. Clearing this file has allowed me to move forward.

```
ubuntu@ip-172-31-36-90:~/.config/hca$ cat config.json
{"DSSClient": {"swagger_url": "https://dss.dev.data.humancellatlas.org/v1/swagger.json"}, "log_level": "INFO", "client_id": "foo"}
```

**Comment by briandoconnor** [comment]
I think this can be closed.  @sampierson
