### ISSUE TITLE
Download Problem - 500 Error

### ISSUE THREAD

**Issue by briandoconnor** [HumanCellAtlas/dcp-preview#10]
I checked on my download in Virginia and saw this:

```
ubuntu@ip-172-31-43-142:~/tmm$ time ../dcp-preview/site/download-scripts/hca-download-melanoma.sh
...
INFO:hca:File 22167_7#47_2.fastq.gz: Retrieving...
INFO:hca:File 22167_7#47_2.fastq.gz: GET SUCCEEDED. Writing to disk.
INFO:hca:File 22167_7#47_2.fastq.gz: GET SUCCEEDED. Stored at ad6e5388-3c31-414e-9f5f-ed3912433348/22167_7#47_2.fastq.gz.
INFO:hca:File file.json: Retrieving...
INFO:hca:File file.json: GET SUCCEEDED. Writing to disk.
INFO:hca:File file.json: GET SUCCEEDED. Stored at ad6e5388-3c31-414e-9f5f-ed3912433348/file.json.
INFO:hca:File process.json: Retrieving...
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/hca", line 13, in <module>
    cli.main()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/hca/cli.py", line 65, in main
    result = parsed_args.entry_point(parsed_args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/hca/util/__init__.py", line 397, in arg_forwarder
    return command(**command_args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/hca/dss/__init__.py", line 41, in download
    response = self.get_file._request(dict(uuid=file_uuid, replica=replica), stream=True)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/hca/util/__init__.py", line 137, in _request
    raise SwaggerAPIException(response=res)
hca.util.exceptions.SwaggerAPIException: Internal Server Error: None (HTTP 500). Details:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>76E8CE82CB8616A1</RequestId><HostId>Kp/TK6N8WQsl1mjD9mIVNcq6fw2Ii2CwhaQVccMkG+QkEWKzEye4sr7XV/HYbXUSFFGTHlEzEcU=</HostId></Error>

real    497m59.787s
user    32m41.924s
sys     14m48.472s
```

The download scripts were from this commit:

```
ubuntu@ip-172-31-43-142:~/dcp-preview$ git log -1 --oneline
472cde7 Rename download scripts
```

**Comment by briandoconnor** [comment]
I restarted my download, it skipped the already downloaded entries as expected and is running again:

```
Skipping f2f04b9f-0fcd-4375-8c13-a659eb8c7048, already downloaded.
Skipping 68f7f700-e3ce-437a-8f59-c1c0fc8b842f, already downloaded.
Skipping f9603dc1-b138-4ded-a3f4-2f9b11d8bd2a, already downloaded.
Skipping 9f523f4d-0165-4101-9cb9-7275138c4343, already downloaded.
Downloading ad6e5388-3c31-414e-9f5f-ed3912433348 to mouse_melanoma/ad6e5388-3c31-414e-9f5f-ed3912433348...
INFO:hca:File project.json: Retrieving...
INFO:hca:File project.json: GET SUCCEEDED. Writing to disk.
INFO:hca:File project.json: GET SUCCEEDED. Stored at ad6e5388-3c31-414e-9f5f-ed3912433348/project.json.
INFO:hca:File biomaterial.json: Retrieving...
INFO:hca:File biomaterial.json: GET SUCCEEDED. Writing to disk.
INFO:hca:File biomaterial.json: GET SUCCEEDED. Stored at ad6e5388-3c31-414e-9f5f-ed3912433348/biomaterial.json.
INFO:hca:File 22167_7#47_1.fastq.gz: Retrieving...
INFO:hca:File 22167_7#47_1.fastq.gz: GET SUCCEEDED. Writing to disk.
INFO:hca:File 22167_7#47_1.fastq.gz: GET SUCCEEDED. Stored at ad6e5388-3c31-414e-9f5f-ed3912433348/22167_7#47_1.fastq.gz.
INFO:hca:File 22167_7#47_2.fastq.gz: Retrieving...
INFO:hca:File 22167_7#47_2.fastq.gz: GET SUCCEEDED. Writing to disk.
...
```

**Comment by kislyuk** [comment]
This should now be fixed with the 500 code added to the retryable series.
