### ISSUE TITLE
Download Problem - ChunkedEncodingError 

### ISSUE THREAD

**Issue by briandoconnor** [HumanCellAtlas/dcp-preview#3]
Unfortunately, this happened on the rica dataset.  I confirmed with `pip list` I have `hca (3.4.2)`.  My other downloads are going still.  I also confirmed my git repo is up to date.

```
INFO:hca:File MantonBM5_HiSeq_3_S3_L002_I1_001.fastq.gz: Retrieving...
INFO:hca:File MantonBM5_HiSeq_3_S3_L002_I1_001.fastq.gz: GET SUCCEEDED. Writing to disk.
INFO:hca:File MantonBM5_HiSeq_3_S3_L002_I1_001.fastq.gz: GET SUCCEEDED. Stored at c94a43f9-257f-4cd0-b2fe-eaf6d5d37d18/MantonBM5_HiSeq_3_S3_L002_I1_001.fastq.gz.
INFO:hca:File MantonBM5_HiSeq_3_S3_L002_R1_001.fastq.gz: Retrieving...
INFO:hca:File MantonBM5_HiSeq_3_S3_L002_R1_001.fastq.gz: GET SUCCEEDED. Writing to disk.
INFO:hca:File MantonBM5_HiSeq_3_S3_L002_R1_001.fastq.gz: GET SUCCEEDED. Stored at c94a43f9-257f-4cd0-b2fe-eaf6d5d37d18/MantonBM5_HiSeq_3_S3_L002_R1_001.fastq.gz.
INFO:hca:File MantonBM5_HiSeq_3_S3_L002_R2_001.fastq.gz: Retrieving...
INFO:hca:File MantonBM5_HiSeq_3_S3_L002_R2_001.fastq.gz: GET SUCCEEDED. Writing to disk.
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/hca", line 13, in <module>
    cli.main()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/hca/cli.py", line 65, in main
    result = parsed_args.entry_point(parsed_args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/hca/util/__init__.py", line 397, in arg_forwarder
    return command(**command_args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/hca/dss/__init__.py", line 48, in download
    for chunk in response.iter_content(chunk_size=1024*1024):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/models.py", line 748, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))
real    63m15.205s
user    1m4.916s
sys     1m25.148s
```

**Comment by ttung** [comment]
This is because urllib3 retry handling does not work with streaming content.  Will need a better solution.

**Comment by briandoconnor** [comment]
Changing the ticket to "ChunkedEncodingError"

I've seen this now on AWS Oregon and Tokyo.

**Comment by kislyuk** [comment]
@ttung please review https://github.com/HumanCellAtlas/dcp-cli/pull/98 which addresses this issue.

**Comment by kislyuk** [comment]
@briandoconnor I think bugs in specific software should be filed in its respective repo. In this case we should file dcp-cli bugs in https://github.com/HumanCellAtlas/dcp-cli/issues.

**Comment by rexwangcc** [comment]
Ran into the same error when downloading the `Melanoma Infiltration of Stromal and Immune Cells` dataset with the latest version of dcp-cli and this repo: 
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/rex/anaconda3/lib/python3.6/site-packages/requests/models.py", line 745, in generate
for chunk in self.raw.stream(chunk_size, decode_content=True):
File "/home/rex/anaconda3/lib/python3.6/site-packages/urllib3/response.py", line 436, in stream
data = self.read(amt=amt, decode_content=decode_content)
File "/home/rex/anaconda3/lib/python3.6/site-packages/urllib3/response.py", line 401, in read
raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
File "/home/rex/anaconda3/lib/python3.6/contextlib.py", line 100, in __exit__
self.gen.throw(type, value, traceback)
File "/home/rex/anaconda3/lib/python3.6/site-packages/urllib3/response.py", line 320, in _error_catcher
raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: OSError("(104, \'ECONNRESET\')",)', OSError("(104, 'ECONNRESET')",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/rex/anaconda3/bin/hca", line 13, in <module>
cli.main()
File "/home/rex/anaconda3/lib/python3.6/site-packages/hca/cli.py", line 65, in main
result = parsed_args.entry_point(parsed_args)
File "/home/rex/anaconda3/lib/python3.6/site-packages/hca/util/__init__.py", line 397, in arg_forwarder
return command(**command_args)
File "/home/rex/anaconda3/lib/python3.6/site-packages/hca/dss/__init__.py", line 48, in download
for chunk in response.iter_content(chunk_size=1024*1024):
File "/home/rex/anaconda3/lib/python3.6/site-packages/requests/models.py", line 748, in generate
raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: OSError("(104, \'ECONNRESET\')",)', OSError("(104, 'ECONNRESET')",))
./hca-download-melanoma.sh 263.37s user 94.02s system 14% cpu 40:44.62 total
```
Post it here to provide more data to the issue.

**Comment by kislyuk** [comment]
This should now be fixed with the retry policy on streaming transfers.
